<?php

namespace App\Models;

use PDO;

/**
 * ===========================
 *  Hrvatski (Croatian)
 * ===========================
 * Model Role definira tablicu 'role' u bazi.
 * - Koristi UUID kao primarni ključ (generira ga baza pomoću UUID()).
 * - Polje 'name' je jedinstveno ime role.
 * - Prilikom inicijalizacije kreira tablicu ako ne postoji.
 * - Automatski dodaje početne role: "Admin" i "Registriran".
 *
 * ===========================
 *  English
 * ===========================
 * The Role model defines the 'role' table in the database.
 * - Uses UUID as primary key (generated by DB with UUID()).
 * - The 'name' field is a unique role name.
 * - On initialization, it creates the table if it does not exist.
 * - Automatically inserts default roles: "Admin" and "Registriran".
 */
class Role extends BaseModel
{
  protected string $table = 'role';

  protected array $fields = [
    'name' => ['type' => 'VARCHAR(50)', 'unique' => true]
  ];

  public function __construct(PDO $pdo)
  {
    parent::__construct($pdo);
    $this->ensureDefaultRoles();
  }

  /**
   * Uvijek osigurava da postoje osnovne role u tablici.
   * Always ensures default roles exist in the table.
   */
  private function ensureDefaultRoles(): void
  {
    $stmt = $this->pdo->query("SELECT COUNT(*) FROM {$this->table}");
    $count = (int) $stmt->fetchColumn();

    if ($count === 0) {
      // HR: Ubaci početne role direktno preko PDO, DB generira UUID() /
      // EN: Insert default roles via PDO, DB generates UUID()
      $stmtIns = $this->pdo->prepare("INSERT INTO {$this->table} (name) VALUES (:name)");
      foreach (['Admin', 'Registriran'] as $roleName) {
        $stmtIns->execute(['name' => $roleName]);
      }
    }
  }


}
